-- Audit trail for answers generated by the RAG advisor.

CREATE TABLE advisor_query_log (
    query_id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_question       TEXT NOT NULL,
    intent               TEXT NOT NULL,
    retrieved_context    JSONB NOT NULL,
    response             TEXT NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_advisor_query_log_created_at
    ON advisor_query_log(created_at DESC);
